name: cell
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blinker=1.9.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2024.12.14
  - click=8.1.8
  - flask=3.1.0
  - git=2.47.1
  - importlib-metadata=8.5.0
  - itsdangerous=2.2.0
  - jinja2=3.1.5
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - libcurl=8.11.1
  - libedit=3.1.20240808
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libiconv=1.17
  - liblzma=5.6.3
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libsqlite=3.48.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - markupsafe=3.0.2
  - ncurses=6.5
  - openssl=3.4.0
  - pcre2=10.44
  - perl=5.32.1
  - pip=24.3.1
  - python=3.10.16
  - python_abi=3.10
  - readline=8.2
  - tk=8.6.13
  - werkzeug=3.1.3
  - wheel=0.45.1
  - zipp=3.21.0
  - zstd=1.5.6
  - pip:
      - astunparse==1.6.3
      - attrs==24.3.0
      - beniget==0.4.2.post1
      - cachetools==5.5.0
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - classification-models==0.1
      - contourpy==1.3.1
      - coverage==7.6.9
      - cycler==0.12.1
      - efficientnet==1.1.1
      - exceptiongroup==1.2.2
      - flask-cors==5.0.0
      - flatbuffers==24.12.23
      - fonttools==4.55.3
      - gast==0.4.0
      - genapi==0.0.8
      - google-auth==2.37.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.69.0
      - hypothesis==6.123.0
      - idna==3.10
      - imagecodecs==2024.12.30
      - imageio==2.36.1
      - iniconfig==2.0.0
      - keras==2.11.0
      - keras-applications==1.0.8
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - libclang==18.1.1
      - lxml==4.9.2
      - markdown==3.7
      - matplotlib==3.7.2
      - mock==5.1.0
      - networkx==3.4.2
      - nose==1.3.7
      - npm==0.1.1
      - numpy==1.26.4
      - oauthlib==3.2.2
      - opencv-python==4.10.0.84
      - opt-einsum==3.4.0
      - optional-django==0.1.0
      - pandas==2.0.3
      - pillow==11.0.0
      - pluggy==1.5.0
      - ply==3.11
      - progressbar33==2.4
      - protobuf==3.19.6
      - psutil==5.9.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycocotools==2.0.8
      - pygments==2.11.2
      - pyparsing==3.0.9
      - pytest==8.3.4
      - python-dateutil==2.9.0.post0
      - pythran==0.17.0
      - pytz==2024.1
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rsa==4.9
      - runtests==0.0.28
      - scikit-image==0.25.0
      - scipy==1.10.1
      - setuptools==75.1.0
      - six==1.16.0
      - slumber==0.7.1
      - sortedcontainers==2.4.0
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.11.0
      - tensorflow-estimator==2.11.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.5.0
      - tifffile==2023.7.10
      - tomli==2.2.1
      - tzdata==2024.2
      - urllib3==2.3.0
      - wrapt==1.17.2
