# 模型配置
#model: yolov11n.pt  # 预训练模型（n为最小版本，可换成s/m/l/x）
epochs: 400         # 训练轮数
batch: 16           # 批次大小
imgsz:  640         # 图像大小
patience: 30        # 早停参数
device: 0           # GPU设备(可用"0,1,2"指定多个GPU)
seed: 200           # 随机种子

# 数据集配置
data: /home/greenbaumgpu/Fengyi/YOLO/datasets/CD3_2_2/images/data.yaml
lr0: 0.0001           # 初始学习率
lrf: 0.01           # 最终学习率因子
momentum: 0.937     # SGD动量
weight_decay: 0.0005 # 权重衰减
warmup_epochs: 3.0  # 预热轮数
warmup_momentum: 0.8 # 预热动量
warmup_bias_lr: 0.1  # 预热偏置学习率

# 数据增强（根据您之前成功训练的参数进行调整）
hsv_h: 0.0        # 色调增强 (保留您原配置的值)
hsv_s: 0.0          # 饱和度增强 (调整为更温和的值)
hsv_v: 0.0          # 值增强 (调整为更温和的值)
degrees: 180.0      # 旋转角度范围(±度数) (保留之前成功的值)
translate: 0.1      # 平移增强(±比例) (调整为之前成功的值)
scale: 0.1          # 缩放增强(±比例) (保留之前成功的值)
shear: 0.1          # 剪切增强(±度数) (调整为之前成功的值，禁用)
perspective: 0.0    # 透视增强(±比例) (调整为之前成功的值，禁用)
flipud: 0.5         # 垂直翻转概率 (调整为之前成功的值)
fliplr: 0.5         # 水平翻转概率 (调整为之前成功的值)
mosaic: 1.0         # 马赛克增强概率 (调整为之前成功的值)
mixup: 0.5          # 混合增强概率 (调整为之前成功的值)

